baseurl = "indogermanschool.netlify.com"
title = "Indo German School"
author = " "
googleAnalytics = ""
defaultContentLanguage = "en"
language = "en-US"
paginate = 3 # Number of posts per page

theme = "hugo-terrassa-theme"
themesDir = "../igs1/themes" # Not necessary on production sites

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML", "RSS"]

[params]
    description = "Terrassa is a simple, fast and responsive theme for Hugo with a strong focus on accessibility made from scratch."
    favicon = " " # Relative URL
    logo = " " # Absolute URL

[params.hero]
    textColor = "beige" # Empty for default color

[params.cta] # Call To Action 
    show = true
    cta = "Contact"
    link = "contact" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true # Use only if you are using Netlify
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Message"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = "info@indogermanschool.com"
    phone = "+91 80 414 422 38"
    skype = ""
    address = "  № 8/P  1st A cross  3rd Main Road Kasturinagar Bangalore – 560043"

[params.social] # Social networks
    twitter = ""
    github = ""
    gitlab = ""
    codepen = ""
	facebook = ""
	instagram = ""
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "Indo German School" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
