/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlaygroupRouteImport } from './routes/playgroup'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard/submissions'
import { Route as DashboardStaffAttendanceRouteImport } from './routes/dashboard/staff-attendance'
import { Route as DashboardSalariesRouteImport } from './routes/dashboard/salaries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMySalariesRouteImport } from './routes/dashboard/my-salaries'
import { Route as DashboardMyAttendanceRouteImport } from './routes/dashboard/my-attendance'
import { Route as DashboardFeesRouteImport } from './routes/dashboard/fees'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as DashboardEnquiriesRouteImport } from './routes/dashboard/enquiries'
import { Route as DashboardDocsRouteImport } from './routes/dashboard/docs'
import { Route as DashboardClassesRouteImport } from './routes/dashboard/classes'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard/attendance'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardStudentsIndexRouteImport } from './routes/dashboard/students.index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff.index'
import { Route as DashboardStudentsNewRouteImport } from './routes/dashboard/students.new'
import { Route as DashboardStudentsStudentIdRouteImport } from './routes/dashboard/students.$studentId'
import { Route as DashboardStaffNewRouteImport } from './routes/dashboard/staff.new'
import { Route as DashboardStaffStaffIdRouteImport } from './routes/dashboard/staff.$staffId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardStaffStaffIdSlipSalaryIdRouteImport } from './routes/dashboard/staff_.$staffId.slip.$salaryId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroupRoute = PlaygroupRouteImport.update({
  id: '/playgroup',
  path: '/playgroup',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffAttendanceRoute =
  DashboardStaffAttendanceRouteImport.update({
    id: '/staff-attendance',
    path: '/staff-attendance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSalariesRoute = DashboardSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMySalariesRoute = DashboardMySalariesRouteImport.update({
  id: '/my-salaries',
  path: '/my-salaries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyAttendanceRoute = DashboardMyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesRoute = DashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentsIndexRoute = DashboardStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsNewRoute = DashboardStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsStudentIdRoute =
  DashboardStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStaffNewRoute = DashboardStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffStaffIdRoute = DashboardStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffStaffIdSlipSalaryIdRoute =
  DashboardStaffStaffIdSlipSalaryIdRouteImport.update({
    id: '/staff_/$staffId/slip/$salaryId',
    path: '/staff/$staffId/slip/$salaryId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/playgroup': typeof PlaygroupRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in': typeof SignInRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-salaries': typeof DashboardMySalariesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/salaries': typeof DashboardSalariesRoute
  '/dashboard/staff-attendance': typeof DashboardStaffAttendanceRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/staff/$staffId': typeof DashboardStaffStaffIdRoute
  '/dashboard/staff/new': typeof DashboardStaffNewRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/staff/$staffId/slip/$salaryId': typeof DashboardStaffStaffIdSlipSalaryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/playgroup': typeof PlaygroupRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in': typeof SignInRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-salaries': typeof DashboardMySalariesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/salaries': typeof DashboardSalariesRoute
  '/dashboard/staff-attendance': typeof DashboardStaffAttendanceRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/staff/$staffId': typeof DashboardStaffStaffIdRoute
  '/dashboard/staff/new': typeof DashboardStaffNewRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/students': typeof DashboardStudentsIndexRoute
  '/dashboard/staff/$staffId/slip/$salaryId': typeof DashboardStaffStaffIdSlipSalaryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/playgroup': typeof PlaygroupRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in': typeof SignInRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-salaries': typeof DashboardMySalariesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/salaries': typeof DashboardSalariesRoute
  '/dashboard/staff-attendance': typeof DashboardStaffAttendanceRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/staff/$staffId': typeof DashboardStaffStaffIdRoute
  '/dashboard/staff/new': typeof DashboardStaffNewRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/staff_/$staffId/slip/$salaryId': typeof DashboardStaffStaffIdSlipSalaryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/playgroup'
    | '/privacy'
    | '/rss.xml'
    | '/sign-in'
    | '/blog/$slug'
    | '/dashboard/attendance'
    | '/dashboard/calendar'
    | '/dashboard/classes'
    | '/dashboard/docs'
    | '/dashboard/enquiries'
    | '/dashboard/expenses'
    | '/dashboard/fees'
    | '/dashboard/my-attendance'
    | '/dashboard/my-salaries'
    | '/dashboard/profile'
    | '/dashboard/salaries'
    | '/dashboard/staff-attendance'
    | '/dashboard/submissions'
    | '/dashboard/users'
    | '/blog/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/staff/$staffId'
    | '/dashboard/staff/new'
    | '/dashboard/students/$studentId'
    | '/dashboard/students/new'
    | '/dashboard/staff/'
    | '/dashboard/students/'
    | '/dashboard/staff/$staffId/slip/$salaryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/playgroup'
    | '/privacy'
    | '/rss.xml'
    | '/sign-in'
    | '/blog/$slug'
    | '/dashboard/attendance'
    | '/dashboard/calendar'
    | '/dashboard/classes'
    | '/dashboard/docs'
    | '/dashboard/enquiries'
    | '/dashboard/expenses'
    | '/dashboard/fees'
    | '/dashboard/my-attendance'
    | '/dashboard/my-salaries'
    | '/dashboard/profile'
    | '/dashboard/salaries'
    | '/dashboard/staff-attendance'
    | '/dashboard/submissions'
    | '/dashboard/users'
    | '/blog'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/staff/$staffId'
    | '/dashboard/staff/new'
    | '/dashboard/students/$studentId'
    | '/dashboard/students/new'
    | '/dashboard/staff'
    | '/dashboard/students'
    | '/dashboard/staff/$staffId/slip/$salaryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/playgroup'
    | '/privacy'
    | '/rss.xml'
    | '/sign-in'
    | '/blog/$slug'
    | '/dashboard/attendance'
    | '/dashboard/calendar'
    | '/dashboard/classes'
    | '/dashboard/docs'
    | '/dashboard/enquiries'
    | '/dashboard/expenses'
    | '/dashboard/fees'
    | '/dashboard/my-attendance'
    | '/dashboard/my-salaries'
    | '/dashboard/profile'
    | '/dashboard/salaries'
    | '/dashboard/staff-attendance'
    | '/dashboard/submissions'
    | '/dashboard/users'
    | '/blog/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/staff/$staffId'
    | '/dashboard/staff/new'
    | '/dashboard/students/$studentId'
    | '/dashboard/students/new'
    | '/dashboard/staff/'
    | '/dashboard/students/'
    | '/dashboard/staff_/$staffId/slip/$salaryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  PlaygroupRoute: typeof PlaygroupRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SignInRoute: typeof SignInRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgroup': {
      id: '/playgroup'
      path: '/playgroup'
      fullPath: '/playgroup'
      preLoaderRoute: typeof PlaygroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff-attendance': {
      id: '/dashboard/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/dashboard/staff-attendance'
      preLoaderRoute: typeof DashboardStaffAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/salaries': {
      id: '/dashboard/salaries'
      path: '/salaries'
      fullPath: '/dashboard/salaries'
      preLoaderRoute: typeof DashboardSalariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-salaries': {
      id: '/dashboard/my-salaries'
      path: '/my-salaries'
      fullPath: '/dashboard/my-salaries'
      preLoaderRoute: typeof DashboardMySalariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-attendance': {
      id: '/dashboard/my-attendance'
      path: '/my-attendance'
      fullPath: '/dashboard/my-attendance'
      preLoaderRoute: typeof DashboardMyAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries': {
      id: '/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries'
      preLoaderRoute: typeof DashboardEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs': {
      id: '/dashboard/docs'
      path: '/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/students/': {
      id: '/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof DashboardStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/new': {
      id: '/dashboard/students/new'
      path: '/students/new'
      fullPath: '/dashboard/students/new'
      preLoaderRoute: typeof DashboardStudentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/$studentId': {
      id: '/dashboard/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/dashboard/students/$studentId'
      preLoaderRoute: typeof DashboardStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/new': {
      id: '/dashboard/staff/new'
      path: '/staff/new'
      fullPath: '/dashboard/staff/new'
      preLoaderRoute: typeof DashboardStaffNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/$staffId': {
      id: '/dashboard/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/dashboard/staff/$staffId'
      preLoaderRoute: typeof DashboardStaffStaffIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff_/$staffId/slip/$salaryId': {
      id: '/dashboard/staff_/$staffId/slip/$salaryId'
      path: '/staff/$staffId/slip/$salaryId'
      fullPath: '/dashboard/staff/$staffId/slip/$salaryId'
      preLoaderRoute: typeof DashboardStaffStaffIdSlipSalaryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardClassesRoute: typeof DashboardClassesRoute
  DashboardDocsRoute: typeof DashboardDocsRoute
  DashboardEnquiriesRoute: typeof DashboardEnquiriesRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardMyAttendanceRoute: typeof DashboardMyAttendanceRoute
  DashboardMySalariesRoute: typeof DashboardMySalariesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSalariesRoute: typeof DashboardSalariesRoute
  DashboardStaffAttendanceRoute: typeof DashboardStaffAttendanceRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStaffStaffIdRoute: typeof DashboardStaffStaffIdRoute
  DashboardStaffNewRoute: typeof DashboardStaffNewRoute
  DashboardStudentsStudentIdRoute: typeof DashboardStudentsStudentIdRoute
  DashboardStudentsNewRoute: typeof DashboardStudentsNewRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardStudentsIndexRoute: typeof DashboardStudentsIndexRoute
  DashboardStaffStaffIdSlipSalaryIdRoute: typeof DashboardStaffStaffIdSlipSalaryIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardClassesRoute: DashboardClassesRoute,
  DashboardDocsRoute: DashboardDocsRoute,
  DashboardEnquiriesRoute: DashboardEnquiriesRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardMyAttendanceRoute: DashboardMyAttendanceRoute,
  DashboardMySalariesRoute: DashboardMySalariesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSalariesRoute: DashboardSalariesRoute,
  DashboardStaffAttendanceRoute: DashboardStaffAttendanceRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStaffStaffIdRoute: DashboardStaffStaffIdRoute,
  DashboardStaffNewRoute: DashboardStaffNewRoute,
  DashboardStudentsStudentIdRoute: DashboardStudentsStudentIdRoute,
  DashboardStudentsNewRoute: DashboardStudentsNewRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardStudentsIndexRoute: DashboardStudentsIndexRoute,
  DashboardStaffStaffIdSlipSalaryIdRoute:
    DashboardStaffStaffIdSlipSalaryIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GalleryRoute: GalleryRoute,
  PlaygroupRoute: PlaygroupRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SignInRoute: SignInRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
